# Generated by Django 3.1.7 on 2021-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_rentability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sugested_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
