# Generated by Django 3.1.7 on 2021-03-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_order'),
        ('orders', '0003_order_sugested_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rentability',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sugested_price',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentability', models.CharField(choices=[('GREAT', 'Great'), ('GOOD', 'Good'), ('BAD', 'Bad')], default='GOOD', max_length=10)),
                ('sugested_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='itens',
            field=models.ManyToManyField(to='orders.OrderItem'),
        ),
    ]
