# Generated by Django 3.1.7 on 2021-03-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210315_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itens',
            new_name='items',
        ),
    ]
