# Generated by Django 3.1.7 on 2021-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210315_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='sugested_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
