# Generated by Django 3.1.7 on 2021-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
