# Generated by Django 3.1.7 on 2021-03-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210307_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
