# Generated by Django 3.1.7 on 2021-03-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer',
            new_name='is_offer',
        ),
    ]
