# Generated by Django 3.1.7 on 2021-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Luiz', max_length=50),
            preserve_default=False,
        ),
    ]
